name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - name: Issue comment
      # You may pin to the exact commit or the version.
      # uses: kyoncy/issue-comment-actions@1b1e351bee044874171a5dc99598257425f6272c
      uses: kyoncy/issue-comment-actions@v1
      with:
        # GitHub token for use by this action.
        token: ${{ github.token }} # optional, default is 
        # Message
        message: "Thank you for opening the issue!" # optional, default is 
